### ISSUE TITLE
Block a function

### ISSUE THREAD

**Issue by Jroge** [1-2020almacen/almacen-client#18]
If a user is not logged in, when he wants to 'Iniciar Contratacion', he has to be redirect to login, and if the user is logged in, show the products to register wich ones the user wants and its amount.

**Comment by Dup1n** [comment]
Part 1.- Redirect login, done.
Part 2.- Show products which ones the user wants and its amount, on wait.

**Comment by Jroge** [comment]
Redirect login, almost done, check the login component and the loginMessage variable.

**Comment by Jroge** [comment]
Redirect login, almost done, after login, redirect to "Iniciar contratacion" que el usuario queria hacer, no volverlo al inicio
