### ISSUE TITLE
Change "Contrataciones pendientes" to "Almacen"

### ISSUE THREAD

**Issue by Jroge** [1-2020almacen/almacen-client#22]
When a user from almacen log in, change the text of the "Contrataciones pendientes" nav-link and put "Almacen" to redirect to product omponent which is a list of all the products of the finalized contratations.
In the product component call products_of_finalized_contratations API

**Comment by pablotardio** [comment]
Navbas with "Contrataciones Pendientes" Done

**Comment by Jroge** [comment]
A better API name to call: products_in_storage

**Comment by pablotardio** [comment]
All Done, API is pendient
